services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  app:
    build: .
    ports:
      - 4000:3000
    environment:
      env_file:
        - .env
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}